- name: hub-nuc-atomic configuration
  hosts: localhost
  vars:
    files: "hub-nuc-atomic_files"
  tasks:

    - name: Check for updates
      ansible.posix.rpm_ostree_upgrade:
        allow_downgrade: false
        cache_only: false
        os: ""
        peer: false
      notify:
        - system reboot

    - name: Install packages
      community.general.rpm_ostree_pkg:
        name: "{{ item }}"
        state: present
      loop:
        - tailscale

    - name: Lightdm configuration
      ansible.builtin.copy:
        src: "{{ files }}/lightdm.conf"
        dest: "/etc/lightdm/lightdm.conf"
        force: true

    - name: Firefox configuration
      ansible.builtin.copy:
        src: "{{ files }}/policies.json"
        dest: "/etc/firefox/policies.json"
        force: true

    - name: Install systemd unit files
      ansible.builtin.copy:
        src: "{{ files }}/{{ item }}"
        dest: "/etc/systemd/system/"
        force: true
      loop:
      - "ansible-pull.timer"
      - "ansible-pull.service"

    - name: Ensure services are enabled/running
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - sshd
        - tailscaled
        - ansible-pull.timer

  handlers:
    - name: system reboot
      ansible.builtin.reboot: